# Provide default configuration
# Different recipes can be defined for different target types

# todo check naming convention for apiVersion
apiVersion: sbomer-project/v1
recipes:
  - type: CONTAINER_IMAGE
    generator:
      name: syft-generator
      version: 1.5.0
    enhancers: []  # Empty for now, can add later

  - type: RPM
    generator:
      name: cyclonedx-maven-plugin
      version: 2.7.9
    enhancers:
      - name: rpm-enhancer
        version: 1.0.0
